name: Test
on:
  push:
    branches: [ "**" ]
    tags: [ "*" ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t", "3.15"]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python }}
          enable-cache: true
      - uses: go-task/setup-task@v1
      - run: task test
